global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: jellybase-prometheus
    site: home-network

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: netdata-parents
    metrics_path: /api/v1/allmetrics
    params:
      format:
        - prometheus_all_hosts
      source:
        - average
    static_configs:
      - targets:
          - jellyhome:19999
          - host.docker.internal:19999

  - job_name: node_exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
          - jellyhome:9100
          - jellyberry:9100
