global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: jellybase-prometheus
    site: home-network

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: node_exporter
    static_configs:
      - targets:
          - host.docker.internal:9100
          - jellyhome:9100
          - jellyberry:9100


  - job_name: loki
    static_configs:
      - targets:
          - loki:3100

  - job_name: promtail
    static_configs:
      - targets:
          - host.docker.internal:9080
          - jellyhome:9080
          - jellyberry:9080
