services:

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "80:3000"
    environment:
      TZ: ${TZ}
      HOMEPAGE_ALLOWED_HOSTS: "jellyhome,jellybase,jellyhome.cheetah-iwato.ts.net,jellybase.cheetah-iwato.ts.net,localhost,127.0.0.1,192.168.1.1,192.168.1.2,100.90.175.59,100.125.86.118,jellyhome:80,jellybase:80,jellyhome.cheetah-iwato.ts.net:80,jellybase.cheetah-iwato.ts.net:80,localhost:80,127.0.0.1:80,192.168.1.1:80,192.168.1.2:80,100.90.175.59:80,100.125.86.118:80,jellyhome:3000,jellybase:3000,localhost:3000,127.0.0.1:3000"
    volumes:
      - /opt/docker/appdata/homepage:/app/config

  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9443:9443"
    environment:
      AGENT_SECRET: ${PORTAINER_AGENT_SECRET}
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/docker/appdata/portainer:/data

  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: ${TZ}
      DOZZLE_REMOTE_AGENT: "192.168.1.2:7007|jellybase|HomeLab,192.168.1.159:7007|jellyberry|HomeLab"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mqtt-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      PUID: "1000"
      PGID: "1000"
      TZ: ${TZ}
    volumes:
      - /opt/docker/appdata/mosquitto/config:/mosquitto/config
      - /opt/docker/appdata/mosquitto/data:/mosquitto/data
      - /opt/docker/appdata/mosquitto/log:/mosquitto/log
